# Generated by Django 4.0.5 on 2022-06-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('age', models.IntegerField(default=0)),
                ('address', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postingdate', models.IntegerField()),
                ('location', models.CharField(default='', max_length=30)),
                ('offeredsalary', models.CharField(max_length=30)),
                ('qualification', models.TextField(default='', max_length=300)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.emp')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
